image: docker:19.03.12
stages:
  # - Build
  - Deploy
# node_build:
#   stage: Build
#   image: node:latest
#   artifacts:
#     name: dist
#     expire_in: 1h
#     paths:
#       - dist
#   script:
#     - npm i && npm run build

upload:
  stage: Deploy
  script:
    - echo "Deploy $(pwd)"
    - docker login -u ${MELAX_REPO_U} -p "${MELAX_REPO_PWD}" ${MELAX_REPO}
    - docker build -t "${MELAX_REPO}/melax:mercury-web-$CI_COMMIT_REF_NAME"  .  && docker push ${MELAX_REPO}/melax:mercury-web-$CI_COMMIT_REF_NAME
    - docker run --rm  -e EKS_CLUSTER=${EKS_CLUSTER} -e AWS_REGION=${AWS_REGION} -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e  AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} newbielj/melaxtechcloud:aws   kc.sh -r app-web

