image: docker:19.03.12
stages:
  - Build
  - Deploy
node_build:
  stage: Build
  image: node:latest
  artifacts:
    name: dist
    expire_in: 1h
    paths:
      - dist
  script:
    - npm i && npm run build

upload:
  stage: Deploy
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PWD}
    - echo "Deploy $(pwd)"
    - docker build -t "newbielj/melaxtechcloud:app-web"  .  && docker push newbielj/melaxtechcloud:app-web
    - docker run --rm  -e AWS_REGION=${AWS_REGION} -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e  AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} newbielj/melaxtechcloud:app-web-1.0  eksctl get cluster && kubectl delete pod $(kubectl get pod | grep app-web | awk '{print $1}')





